[package]
name = "stormdb-monitor"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { workspace = true }
anyhow = { workspace = true }
ratatui = "0.26"
crossterm = "0.27"
clap = { workspace = true }
