[package]
name = "stormdb-protocol"
version = "0.1.0"
edition = "2024"

[dependencies]
bytes = { workspace = true }
stormdb-common = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
criterion = { workspace = true }

[[bench]]
name = "protocol_bench"
harness = false
